Return-Path: <linux-kernel-owner@vger.kernel.org>
X-Original-To: lists+linux-kernel@lfdr.de
Delivered-To: lists+linux-kernel@lfdr.de
Received: from out1.vger.email (out1.vger.email [IPv6:2620:137:e000::1:20])
	by mail.lfdr.de (Postfix) with ESMTP id 2E36172FD1F
	for <lists+linux-kernel@lfdr.de>; Wed, 14 Jun 2023 13:41:01 +0200 (CEST)
Received: (majordomo@vger.kernel.org) by vger.kernel.org via listexpand
        id S234968AbjFNLk5 (ORCPT <rfc822;lists+linux-kernel@lfdr.de>);
        Wed, 14 Jun 2023 07:40:57 -0400
Received: from lindbergh.monkeyblade.net ([23.128.96.19]:50270 "EHLO
        lindbergh.monkeyblade.net" rhost-flags-OK-OK-OK-OK) by vger.kernel.org
        with ESMTP id S244329AbjFNLkC (ORCPT
        <rfc822;linux-kernel@vger.kernel.org>);
        Wed, 14 Jun 2023 07:40:02 -0400
Received: from smtp-out1.suse.de (smtp-out1.suse.de [IPv6:2001:67c:2178:6::1c])
        by lindbergh.monkeyblade.net (Postfix) with ESMTPS id 313A319B5
        for <linux-kernel@vger.kernel.org>; Wed, 14 Jun 2023 04:39:27 -0700 (PDT)
Received: from imap2.suse-dmz.suse.de (imap2.suse-dmz.suse.de [192.168.254.74])
        (using TLSv1.3 with cipher TLS_AES_256_GCM_SHA384 (256/256 bits)
         key-exchange X25519 server-signature ECDSA (P-521) server-digest SHA512)
        (No client certificate requested)
        by smtp-out1.suse.de (Postfix) with ESMTPS id D2975223B2;
        Wed, 14 Jun 2023 11:39:25 +0000 (UTC)
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=suse.de; s=susede2_rsa;
        t=1686742765; h=from:from:reply-to:date:date:message-id:message-id:to:to:cc:cc:
         mime-version:mime-version:content-type:content-type:
         in-reply-to:in-reply-to:references:references;
        bh=D8T3hvxpKhTd+SYmVBu2dSFpvNLIFBT4l+91bELI0KI=;
        b=07UdI+UrMXyfyZR0G8X4mpXQR3Cc8m41bhHlpSMEBpg5E1F9/8rzLNDuEC+mycP8XdpdQJ
        xmHd3dfNJJ782xIQE1KzMc9yU5EQtqSQiWT3WOnWGoQzSMq4yiLfZYWwlcXh15+2XYn0L+
        f7onX3kfTsf9FhhNtmFC1mgEuq37AWA=
DKIM-Signature: v=1; a=ed25519-sha256; c=relaxed/relaxed; d=suse.de;
        s=susede2_ed25519; t=1686742765;
        h=from:from:reply-to:date:date:message-id:message-id:to:to:cc:cc:
         mime-version:mime-version:content-type:content-type:
         in-reply-to:in-reply-to:references:references;
        bh=D8T3hvxpKhTd+SYmVBu2dSFpvNLIFBT4l+91bELI0KI=;
        b=3oXH39uRzpcrVMfxBbTBEbHK864JeOgzRPrg9EUEsW4ko9c2YV04NT67dUCtASBP7FQZ/R
        9hGN6FZcp3DsCrCg==
Received: from imap2.suse-dmz.suse.de (imap2.suse-dmz.suse.de [192.168.254.74])
        (using TLSv1.3 with cipher TLS_AES_256_GCM_SHA384 (256/256 bits)
         key-exchange X25519 server-signature ECDSA (P-521) server-digest SHA512)
        (No client certificate requested)
        by imap2.suse-dmz.suse.de (Postfix) with ESMTPS id 479DD1357F;
        Wed, 14 Jun 2023 11:39:25 +0000 (UTC)
Received: from dovecot-director2.suse.de ([192.168.254.65])
        by imap2.suse-dmz.suse.de with ESMTPSA
        id GaL9D+2miWSYIAAAMHmgww
        (envelope-from <tiwai@suse.de>); Wed, 14 Jun 2023 11:39:25 +0000
Date:   Wed, 14 Jun 2023 13:39:24 +0200
Message-ID: <87jzw69ssz.wl-tiwai@suse.de>
From:   Takashi Iwai <tiwai@suse.de>
To:     Lukasz Tyl <ltyl@hem-e.com>
Cc:     perex@perex.cz, tiwai@suse.com, alsa-devel@alsa-project.org,
        linux-kernel@vger.kernel.org, pgorgon@hem-e.com
Subject: Re: [PATCH] sound: usb: quirks: add flag for HEM devices to enable native DSD playback
In-Reply-To: <20230614113350.25607-1-ltyl@hem-e.com>
References: <20230614113350.25607-1-ltyl@hem-e.com>
User-Agent: Wanderlust/2.15.9 (Almost Unreal) Emacs/27.2 Mule/6.0
MIME-Version: 1.0 (generated by SEMI-EPG 1.14.7 - "Harue")
Content-Type: text/plain; charset=US-ASCII
X-Spam-Status: No, score=-4.4 required=5.0 tests=BAYES_00,DKIM_SIGNED,
        DKIM_VALID,DKIM_VALID_AU,DKIM_VALID_EF,RCVD_IN_DNSWL_MED,SPF_HELO_NONE,
        SPF_PASS,T_SCC_BODY_TEXT_LINE,URIBL_BLOCKED autolearn=ham
        autolearn_force=no version=3.4.6
X-Spam-Checker-Version: SpamAssassin 3.4.6 (2021-04-09) on
        lindbergh.monkeyblade.net
Precedence: bulk
List-ID: <linux-kernel.vger.kernel.org>
X-Mailing-List: linux-kernel@vger.kernel.org

On Wed, 14 Jun 2023 13:33:50 +0200,
Lukasz Tyl wrote:
> 
> This commit adds new DEVICE_FLG with QUIRK_FLAG_DSD_RAW and Vendor Id for
> HEM devices which supports native DSD. Prior to this change Linux kernel
> was not enabling native DSD playback for HEM devices, and as a result,
> DSD audio was being converted to PCM "on the fly". HEM devices,
> when connected to the system, would only play audio in PCM format,
> even if the source material was in DSD format. With the addition of new
> VENDOR_FLG in the quircks.c file, the devices are now correctly
> recognized, and raw DSD data is transmitted to the device,
> allowing for native DSD playback.
> 
> Signed-off-by: Lukasz Tyl <ltyl@hem-e.com>
> ---
>  sound/usb/quirks.c | 2 ++
>  1 file changed, 2 insertions(+)
> 
> diff --git a/sound/usb/quirks.c b/sound/usb/quirks.c
> index 3ecd1ba7fd4b..1414bf15ac21 100644
> --- a/sound/usb/quirks.c
> +++ b/sound/usb/quirks.c
> @@ -2197,6 +2197,8 @@ static const struct usb_audio_quirk_flags_table quirk_flags_table[] = {
>  		   QUIRK_FLAG_DSD_RAW),
>  	VENDOR_FLG(0xc502, /* HiBy devices */
>  		   QUIRK_FLAG_DSD_RAW),
> +	VENDOR_FLG(0x3336, /* HEM devices */
> +		   QUIRK_FLAG_DSD_RAW),

The entry is sorted in vendor id number.  Could you try to put at the
right position?


thanks,

Takashi
